/* Generated By:JavaCC: Do not edit this line. LexerConstants.java */
package edu.purdue.cs352.minijava.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_CLASS = 8;
  /** RegularExpression Id. */
  int KW_PUBLIC = 9;
  /** RegularExpression Id. */
  int KW_STATIC = 10;
  /** RegularExpression Id. */
  int KW_VOID = 11;
  /** RegularExpression Id. */
  int KW_MAIN = 12;
  /** RegularExpression Id. */
  int KW_STRING = 13;
  /** RegularExpression Id. */
  int KW_EXTENDS = 14;
  /** RegularExpression Id. */
  int KW_RETURN = 15;
  /** RegularExpression Id. */
  int KW_INT = 16;
  /** RegularExpression Id. */
  int KW_BOOLEAN = 17;
  /** RegularExpression Id. */
  int KW_IF = 18;
  /** RegularExpression Id. */
  int KW_ELSE = 19;
  /** RegularExpression Id. */
  int KW_WHILE = 20;
  /** RegularExpression Id. */
  int KW_TRUE = 21;
  /** RegularExpression Id. */
  int KW_FALSE = 22;
  /** RegularExpression Id. */
  int KW_THIS = 23;
  /** RegularExpression Id. */
  int KW_NEW = 24;
  /** RegularExpression Id. */
  int KW_SYSPRNT = 25;
  /** RegularExpression Id. */
  int SYM_LBRACE = 26;
  /** RegularExpression Id. */
  int SYM_RBRACE = 27;
  /** RegularExpression Id. */
  int SYM_LPAREN = 28;
  /** RegularExpression Id. */
  int SYM_RPAREN = 29;
  /** RegularExpression Id. */
  int SYM_LBRACK = 30;
  /** RegularExpression Id. */
  int SYM_RBRACK = 31;
  /** RegularExpression Id. */
  int SYM_SEMICOL = 32;
  /** RegularExpression Id. */
  int SYM_EQ = 33;
  /** RegularExpression Id. */
  int SYM_LOGAND = 34;
  /** RegularExpression Id. */
  int SYM_LOGOR = 35;
  /** RegularExpression Id. */
  int SYM_LESS = 36;
  /** RegularExpression Id. */
  int SYM_LESSEQ = 37;
  /** RegularExpression Id. */
  int SYM_EQEQ = 38;
  /** RegularExpression Id. */
  int SYM_NOTEQ = 39;
  /** RegularExpression Id. */
  int SYM_GREAT = 40;
  /** RegularExpression Id. */
  int SYM_GREATEQ = 41;
  /** RegularExpression Id. */
  int SYM_PLUS = 42;
  /** RegularExpression Id. */
  int SYM_MINUS = 43;
  /** RegularExpression Id. */
  int SYM_MULTIL = 44;
  /** RegularExpression Id. */
  int SYM_DIVIDE = 45;
  /** RegularExpression Id. */
  int SYM_MOD = 46;
  /** RegularExpression Id. */
  int SYM_NOT = 47;
  /** RegularExpression Id. */
  int SYM_DOT = 48;
  /** RegularExpression Id. */
  int SYM_COMMA = 49;
  /** RegularExpression Id. */
  int IDENTIFIER = 50;
  /** RegularExpression Id. */
  int INT_LITERAL = 51;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"String\"",
    "\"extends\"",
    "\"return\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"System.out.println\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\".\"",
    "\",\"",
    "<IDENTIFIER>",
    "<INT_LITERAL>",
  };

}
